/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/items/': RouteRecordInfo<'/items/', '/items', Record<never, never>, Record<never, never>>,
    '/payments/': RouteRecordInfo<'/payments/', '/payments', Record<never, never>, Record<never, never>>,
    '/payments/register': RouteRecordInfo<'/payments/register', '/payments/register', Record<never, never>, Record<never, never>>,
  }
}
